steps:
  - name: Build and publish container image
    agents:
      queue: default
      os: linux
    plugins:
      - EmbarkStudios/k8s#0.9.2:
          image: gcr.io/kaniko-project/executor:latest
          command:
            - --destination=embarkstudios/packer-qemu
            - --context=dir://$PWD
            - --reproducible
            - --cache=true
            - --cache-dir=$BUILDKITE_BUILD_PATH/_kaniko_cache
          mount-secret:
            - docker-hub-credentials:/kaniko/.docker
